apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
      - name: rating
        image: aldrich814/metareviews_rating:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 808
